# Generated by Django 5.1.7 on 2025-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteenattendance',
            options={'verbose_name_plural': 'Canteen Attendances'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
